Write error on sterr

diff --git a/bin/bw b/bin/bw
--- a/bin/bw
+++ b/bin/bw
@@ -1,14 +1,15 @@
+
 #!/usr/bin/env bash
 
 dev="$1"
-if [[ -z "${dev}" ]]; then 
-    echo "Usage: $(basename $0) INTERFACE"
-    echo "Display bandwith (up and down) for an interface"
+if [[ -z "${dev}" ]]; then
+    echo >&2 "Usage: $(basename $0) INTERFACE"
+    echo >&2 "Display bandwith (up and down) for an interface"
     exit 1
-elif ! grep -q "^ *${dev}:" /proc/net/dev; then 
-    echo "error: device '${dev}' not found"
-    echo "avalaible devices:"
-    grep ':' /proc/net/dev | awk -F: '{print $1}' | sed 's,^\s*,- ,' 
+elif ! grep -q "^ *${dev}:" /proc/net/dev; then
+    echo >&2 "error: device '${dev}' not found"
+    #echo "avalaible devices:"
+    #grep ':' /proc/net/dev | awk -F: '{print $1}' | sed 's,^\s*,- ,'
     exit 2
 fi
 
diff --git a/bin/mvi b/bin/mvi
--- a/bin/mvi
+++ b/bin/mvi
@@ -5,7 +5,7 @@ set -eu
 # USAGE: vimv [file1 file2]
 # adapted from https://github.com/thameera/vimv
 
-declare -r FILENAMES_FILE=$(mktemp "${TMPDIR:-/tmp}/vimv.XXX")
+FILENAMES_FILE=$(mktemp "${TMPDIR:-/tmp}/vimv.XXX")
 
 trap '{ rm -f "${FILENAMES_FILE}" ; }' EXIT
 
@@ -22,14 +22,15 @@ done
 checksum1="$(md5sum "${FILENAMES_FILE}")"
 ${EDITOR:-vi} "${FILENAMES_FILE}"
 checksum2="$(md5sum "${FILENAMES_FILE}")"
+
 if [[ "${checksum1}" == "${checksum2}" ]]; then
     echo "nothing to do"
-    exit 2
+    exit 0
 fi
 
 IFS=$'\r\n' GLOBIGNORE='*' command eval 'dest=($(cat "${FILENAMES_FILE}"))'
 if [[ "${#src[@]}" != "${#dest[@]}" ]]; then
-    echo "error: source and destination number of files differs"
+    echo >&2 "error: source and destination number of files differs"
     exit 1
 fi
 
