Add new utils + misc fixes

diff --git a/bin/certinfo b/bin/certinfo
--- a/bin/certinfo
+++ b/bin/certinfo
@@ -1,23 +1,28 @@
 #!/usr/bin/env sh
 
+usage(){
+    echo "Usage: $(basename "${0}") DOMAIN"
+    echo 'Display basic certificate information from a domain'
+}
+
 # check required package
 if ! command -v openssl 2>&1 >/dev/null; then
-    echo "Error: openssl is required"
+    echo >&2 'Error: openssl is required'
     exit 1
+fi
+
+if [ ${#} -eq 0 ]; then
+    usage; exit 1
+elif [ "${1}" = '-h' ] || [ "${1}" = '--help' ] ; then
+    usage; exit 0
 fi
 
 domain="$(echo "${1}" | sed 's,^https://,,')"
-if [ -z "${domain}" ]; then
-    echo >&2 "Usage: $(basename "${0}") DOMAIN"
-    echo >&2 "Display basic certificate information from a domain"
-    exit 1
-fi
-
+echo "domain\t${domain}"
 echo | openssl s_client -connect "${domain}:443" -prexit 2>/dev/null \
      | openssl x509 -issuer -subject -enddate -fingerprint -noout -ext subjectAltName \
      | sed -e '/^X509v3 Subject Alternative Name/d' \
-          -e 's/^notAfter/expire/' \
-          -e 's/^SHA1 Fingerprint/sha1/' \
-          -e 's/^\s\s*/alt=/' \
-          -e 's/=/\t/'
-
+           -e 's/^notAfter/expire/' \
+           -e 's/^SHA1 Fingerprint/sha1/' \
+           -e 's/^\s\s*/alt=/' \
+           -e 's/=/\t/'
diff --git a/bin/dataurl b/bin/dataurl
--- a/bin/dataurl
+++ b/bin/dataurl
@@ -1,20 +1,25 @@
 #!/usr/bin/env sh
 
+usage(){
+    echo "Usage: $(basename "${0}") FILE"
+    echo 'Convert a file into a base64 encoded url'
+}
+
 # check required package
 if ! command -v file 2>&1 >/dev/null; then
-    echo "Error: file command is required"
+    echo >&2 'Error: file command is required'
     exit 1
 fi
 
-if [ -z "${1}" ]; then
-    echo >&2 "Usage: $(basename "${0}") FILE"
-    echo >&2 'Convert a file into a base64 encoded url'
-    exit 1
+if [ ${#} -eq 0 ]; then
+    usage; exit 1
+elif [ "${1}" = '-h' ] || [ "${1}" = '--help' ] ; then
+    usage; exit 0
 fi
 
-mimeType=$(file -b --mime-type "${1}")
-if echo ${mimeType} | grep -q '^text/'; then
-    mimeType="${mimeType};charset=utf-8";
+mime_type=$(file --brief --mime-type "${1}")
+if echo "${mime_type}" | grep -q '^text/'; then
+    mime_type="${mime_type};charset=utf-8";
 fi
-echo "data:${mimeType};base64,$(base64 "${1}" | tr -d '\n')";
 
+echo "data:${mime_type};base64,$(base64 "${1}" | tr -d '\n')"
diff --git a/bin/httpstatus b/bin/httpstatus
--- a/bin/httpstatus
+++ b/bin/httpstatus
@@ -1,17 +1,22 @@
 #!/usr/bin/env bash
 
+usage(){
+    echo "Usage: $(basename "${0}") URL"
+    echo 'Display http(s) status code from an url'
+}
+
 # check required package
 if ! command -v curl >/dev/null 2>&1; then
-    echo "Error: curl is required"
+    echo >&2 'Error: curl is required'
     exit 1
 fi
 
-if [ -z "${1}" ]; then
-    echo >&2 "Usage: $(basename "${0}") URL"
-    echo >&2 'Display http(s) status code from an url'
-    exit 1
+if [ ${#} -ne 1 ]; then
+    usage; exit 1
+elif [ "${1}" = '-h' ] || [ "${1}" = '--help' ] ; then
+    usage; exit 0
 fi
+
 useragent="User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) "
 useragent="${useragent}AppleWebKit/537.36 (K HTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
 curl -skLo /dev/null -H "${useragent}" -w "%{http_code}\n" "${1}"
-
diff --git a/bin/mtailf b/bin/mtailf
--- a/bin/mtailf
+++ b/bin/mtailf
@@ -1,9 +1,14 @@
 #!/usr/bin/env bash
 
-if [[ -z "${1}" ]]; then
-    echo >&2 "Usage: $(basename "${0}") FILE [FILE ...]"
-    echo >&2 'Mutliple grouped tailf'
-    exit 1
+usage(){
+    echo "Usage: $(basename "${0}") FILE [FILE ...]"
+    echo 'Mutliple grouped tailf'
+}
+
+if [ ${#} -eq 0 ]; then
+    usage; exit 1
+elif [ "${1}" = '-h' ] || [ "${1}" = '--help' ] ; then
+    usage; exit 0
 fi
 
 # print with a fixed width
@@ -14,16 +19,20 @@ trap 'kill $(jobs -p) &> /dev/null' SIGHUP SIGINT SIGTERM
 
 # get longest filename
 maxlen=0
-for F in "${@}"; do
-    len="$(basename "${F}" | wc -c)"
+for file in "${@}"; do
+    len="$(basename "${file}" | wc -c)"
     (( len > maxlen )) && maxlen="${len}"
 done
 
 # tailling files
-for F in "${@}"; do
-    echo "reading ${F}"
-    filename="$(basename "${F}")"
-    tail -n 0 -f "${F}" 2>/dev/null | while read -r line; do
+for file in "${@}"; do
+    if ! [ -f "${file}" ]; then
+        echo >&2 "Error: no such file '${file}'"
+        continue
+    fi
+    echo "reading ${file}"
+    filename="$(basename "${file}")"
+    tail -n 0 -f "${file}" 2>/dev/null | while read -r line; do
         echo "$(_p "${maxlen}" "${filename}")| "${line}""
     done &
 done
diff --git a/bin/mvi b/bin/mvi
--- a/bin/mvi
+++ b/bin/mvi
@@ -1,50 +1,54 @@
-#!/usr/bin/env bash
-# Lists the current directory's files in Vim, so you can edit it and save to rename them
-# USAGE: vimv [file1 file2]
-# adapted from https://github.com/thameera/vimv
+#!/usr/bin/env sh
 set -eu
 
-FILENAMES_FILE=$(mktemp "${TMPDIR:-/tmp}/vimv.XXX")
+usage() {
+    echo "Usage: $(basename "${0}") FILE [FILE...]"
+    echo 'Bulk rename files using your favorite text editor'
+}
 
-trap '{ rm -f "${FILENAMES_FILE}" ; }' EXIT
+# Setup temporary files
+src_list=$(mktemp "${TMPDIR:-/tmp}/mvi_src.XXX")
+dst_list=$(mktemp "${TMPDIR:-/tmp}/mvi_dst.XXX")
+trap "rm -f '${src_list}' '${dst_list}'" EXIT
 
-if [ $# -ne 0 ]; then
-    src=( "$@" )
-else
-    IFS=$'\r\n' GLOBIGNORE='*' command eval 'src=($(ls))'
+if [ ${#} -eq 0 ]; then
+    # Default to all files/dirs in current path
+    set -- * .[!.]* ..?*
+elif [ "${1}" = '-h' ] || [ "${1}" = '--help' ] ; then
+    usage; exit 0
 fi
 
-for ((i=0;i<${#src[@]};++i)); do
-    echo "${src[i]}" >> "${FILENAMES_FILE}"
-done
+# Add requested files to list
+for f in "${@}"; do 
+    [ -e "${f}" ] && echo "${f}"
+done > "${src_list}"
 
-checksum1="$(md5sum "${FILENAMES_FILE}")"
-${EDITOR:-vi} "${FILENAMES_FILE}"
-checksum2="$(md5sum "${FILENAMES_FILE}")"
+cp "${src_list}" "${dst_list}"
+${EDITOR:-vi} "${dst_list}"
 
-if [[ "${checksum1}" == "${checksum2}" ]]; then
-    echo "nothing to do"
+if cmp -s "${src_list}" "${dst_list}"; then
+    echo "Nothing to do"
     exit 0
-fi
-
-IFS=$'\r\n' GLOBIGNORE='*' command eval 'dest=($(cat "${FILENAMES_FILE}"))'
-if [[ "${#src[@]}" != "${#dest[@]}" ]]; then
-    echo >&2 "error: source and destination number of files differs"
+elif ! wc -l "${src_list}" "${dst_list}" | awk 'NR==1{n=$1} NR==2{exit (n!=$1)}'; then
+    echo >&2 'Error: source and destination number of lines differs'
     exit 1
 fi
 
-declare -i count=0
-for ((i=0;i<${#src[@]};++i)); do
-    if [ "${src[i]}" != "${dest[i]}" ]; then
-        mkdir -p "$(dirname "${dest[i]}")"
-        echo "${src[i]} -> ${dest[i]}"
-        if git ls-files --error-unmatch "${src[i]}" > /dev/null 2>&1; then
-            git mv "${src[i]}" "${dest[i]}"
+count=0
+# Read both files at the same time and process renames line-by-line
+while read -r src <&3 && read -r dst <&4; do
+    if [ "${src}" != "${dst}" ]; then
+        mkdir -p "$(dirname "${dst}")"
+        echo "${src} -> ${dst}"
+        if [ -e "${dst}" ]; then
+            echo >&2 "Warning: Can't proceed, destination exists!"
+            continue
+        elif git ls-files --error-unmatch "${src}" >/dev/null 2>&1; then
+            git mv -- "${src}" "${dst}"
         else
-            mv "${src[i]}" "${dest[i]}"
+            mv -n -- "${src}" "${dst}"
         fi
-        ((++count))
+        count=$((count + 1))
     fi
-done
-
-echo "$count" files renamed.
+done 3<"${src_list}" 4<"${dst_list}"
+echo "${count} files renamed"
diff --git a/bin/stw b/bin/stw
--- a/bin/stw
+++ b/bin/stw
@@ -1,18 +1,24 @@
 #!/usr/bin/env sh
 
-if [ "$#" -eq '0' ]; then
-    echo >&2 "Usage: $(basename "${0}") FILE [FILE...]"
-    echo >&2 "Strip trailing whitespaces of files"
-    exit 1
+usage(){
+    echo "Usage: $(basename "${0}") FILE [FILE...]"
+    echo 'Strip trailing whitespaces of files'
+}
+
+if [ ${#} -eq 0 ]; then
+    usage; exit 1
+elif [ "${1}" = '-h' ] || [ "${1}" = '--help' ] ; then
+    usage; exit 0
 fi
 
 for e in "${@}"; do
-    if [ -f "${e}" ]; then
-        echo "+ ${e}"
-        # print
-        awk '/ +$/ {print $0"."}' "${e}"
-        # replace
-        sed -e 's,\s\s*$,,' -i "${e}"
+    if ! [ -f "${e}" ]; then
+        echo >&2 "Error: no such file '${e}'"
+        continue
     fi
+    echo "+ ${e}"
+    # print
+    awk '/ +$/ {print $0"."}' "${e}"
+    # replace
+    sed -e 's,\s\s*$,,' -i "${e}"
 done
-
