Add binaries: lock, speedtest and tm

diff --git a/bin/dataurl b/bin/dataurl
--- a/bin/dataurl
+++ b/bin/dataurl
@@ -7,12 +7,11 @@ usage(){
 
 # check required package
 if ! command -v file 2>&1 >/dev/null; then
-    echo >&2 'Error: file command is required'
-    exit 1
+    echo 'Error: file command is required' >&2; exit 1
 fi
 
 if [ ${#} -eq 0 ]; then
-    usage; exit 1
+    usage >&2; exit 1
 elif [ "${1}" = '-h' ] || [ "${1}" = '--help' ] ; then
     usage; exit 0
 fi
diff --git a/bin/httpstatus b/bin/httpstatus
--- a/bin/httpstatus
+++ b/bin/httpstatus
@@ -7,12 +7,11 @@ usage(){
 
 # check required package
 if ! command -v curl >/dev/null 2>&1; then
-    echo >&2 'Error: curl is required'
-    exit 1
+    echo 'Error: curl is required' >&2; exit 1
 fi
 
 if [ ${#} -ne 1 ]; then
-    usage; exit 1
+    usage >&2; exit 1
 elif [ "${1}" = '-h' ] || [ "${1}" = '--help' ] ; then
     usage; exit 0
 fi
diff --git a/bin/net b/bin/net
--- a/bin/net
+++ b/bin/net
@@ -27,7 +27,7 @@ while [ ${#} -gt 0 ]; do
     case "${1}" in
         -o|--output)   fields="${2}"; shift 2;;
         -h|--help)     usage; exit 0;;
-        *)             echo >&2 "Unknown option: ${1}"; usage; exit 1;;
+        *)             echo "Unknown option: ${1}" >&2; usage >&2; exit 1;;
     esac
 done
 
@@ -36,8 +36,7 @@ $(ip route get 1.0.0.0 2>/dev/null)
 EOF
 
 if [ -z "${iface}" ]; then
-    echo >&2 'Error: Could not retrieve network data.'
-    exit 1
+    echo 'Error: Could not retrieve network data.' >&2; exit 1
 fi
 
 masklen=$(ip -o -f inet addr show dev "${iface}" | awk '/scope global/ {split($4,v,"/"); print v[2]; exit}')
